# Generated by Django 5.1 on 2024-08-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hamsters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_home', models.CharField(max_length=64)),
                ('hhometext', models.TextField()),
                ('h_eat', models.CharField(max_length=64)),
                ('heattext', models.TextField()),
                ('h_toy', models.CharField(max_length=64)),
                ('htoytext', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='cats',
            old_name='eat_text',
            new_name='ceattext',
        ),
        migrations.RenameField(
            model_name='cats',
            old_name='home_text',
            new_name='chometext',
        ),
        migrations.RenameField(
            model_name='cats',
            old_name='med_text',
            new_name='cmedtext',
        ),
        migrations.RenameField(
            model_name='cats',
            old_name='toy_text',
            new_name='ctoytext',
        ),
        migrations.RenameField(
            model_name='dogs',
            old_name='eattext',
            new_name='deattext',
        ),
        migrations.RenameField(
            model_name='dogs',
            old_name='hometext',
            new_name='dhometext',
        ),
        migrations.RenameField(
            model_name='dogs',
            old_name='medtext',
            new_name='dmedtext',
        ),
        migrations.RenameField(
            model_name='dogs',
            old_name='toytext',
            new_name='dtoytext',
        ),
    ]
