# Generated by Django 5.1 on 2024-08-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_hamsters_rename_eat_text_cats_ceattext_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cats',
            name='cimg',
            field=models.ImageField(default='default_image.jpg', upload_to='p_img'),
        ),
        migrations.AddField(
            model_name='dogs',
            name='dimg',
            field=models.ImageField(default='default_image.jpg', upload_to='p_img'),
        ),
        migrations.AddField(
            model_name='hamsters',
            name='himg',
            field=models.ImageField(default='default_image.jpg', upload_to='p_img'),
        ),
    ]
