# Generated by Django 5.1 on 2024-08-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_cats_cimg_dogs_dimg_hamsters_himg'),
    ]

    operations = [
        migrations.AddField(
            model_name='cats',
            name='chead',
            field=models.CharField(default='default', max_length=64),
        ),
        migrations.AddField(
            model_name='dogs',
            name='dhead',
            field=models.CharField(default='default', max_length=64),
        ),
        migrations.AddField(
            model_name='hamsters',
            name='hhead',
            field=models.CharField(default='default', max_length=64),
        ),
    ]
