# Generated by Django 5.1 on 2024-08-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_cats_chead_dogs_dhead_hamsters_hhead'),
    ]

    operations = [
        migrations.AddField(
            model_name='cats',
            name='ceattextimg',
            field=models.ImageField(default='default_image.jpg', upload_to='p_img'),
        ),
        migrations.AddField(
            model_name='cats',
            name='chometextimg',
            field=models.ImageField(default='default_image.jpg', upload_to='p_img'),
        ),
        migrations.AddField(
            model_name='cats',
            name='cmedtextimg',
            field=models.ImageField(default='default_image.jpg', upload_to='p_img'),
        ),
        migrations.AddField(
            model_name='cats',
            name='ctoytextimg',
            field=models.ImageField(default='default_image.jpg', upload_to='p_img'),
        ),
        migrations.AddField(
            model_name='dogs',
            name='deattextimg',
            field=models.ImageField(default='default_image.jpg', upload_to='p_img'),
        ),
        migrations.AddField(
            model_name='dogs',
            name='dhometextimg',
            field=models.ImageField(default='default_image.jpg', upload_to='p_img'),
        ),
        migrations.AddField(
            model_name='dogs',
            name='dmedtextimg',
            field=models.ImageField(default='default_image.jpg', upload_to='p_img'),
        ),
        migrations.AddField(
            model_name='dogs',
            name='dtoytextimg',
            field=models.ImageField(default='default_image.jpg', upload_to='p_img'),
        ),
        migrations.AddField(
            model_name='hamsters',
            name='heattextimg',
            field=models.ImageField(default='default_image.jpg', upload_to='p_img'),
        ),
        migrations.AddField(
            model_name='hamsters',
            name='hhometextimg',
            field=models.ImageField(default='default_image.jpg', upload_to='p_img'),
        ),
        migrations.AddField(
            model_name='hamsters',
            name='htoytextimg',
            field=models.ImageField(default='default_image.jpg', upload_to='p_img'),
        ),
    ]
